version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/online-attendnace/ # S3에서 받아온 프로젝트 위치
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    
      