# workflow 이름 지정
name: deploy to aws

# 이 workflow가 언제 실행될 것인가?
on:
  # 특정 브랜치가 Push 되는 경우 실행
  #push:
    #branches:
      
  # 특정 브랜치가 Pull Request 되는 경우 실행
  #pull_request:
    #branches:
      #- "**"

  # 수동으로 workflow 실행 가능 -> 자동 실행보다는 수동으로 빌드/배포 실행하는게 더 안전?
  workflow_dispatch:

env: # 새로 추가한 부분
  S3_BUCKET_NAME: online-attendance-deploy
  PROJECT_NAME: online-attendance-server

# 한 workflow는 한 개 또는 여러 개의 jobs를 설정할 수 있다.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 깃허브가 제공하는 워크스페이스(이 workflow를 실행하는 공간)에서 내 저장소가 위치한 곳으로 이동
      - name: Checkout
        uses: actions/checkout@v3
        
      # 자바 설치 및 gradlew에 실행 권한 부여 및 프로젝트 build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

        ### 새로 추가한 부분 ###
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
