# workflow 이름 지정
name: deploy to Koyeb

# 이 workflow가 언제 실행될 것인가?
on:
  # 특정 브랜치가 Push 되는 경우 실행
  #push:
    #branches:
      
  # 특정 브랜치가 Pull Request 되는 경우 실행
  #pull_request:
    #branches:
      #- "**"

  # 수동으로 workflow 실행 가능 -> 자동 실행보다는 수동으로 빌드/배포 실행하는게 더 안전?
  workflow_dispatch:

# 한 workflow는 한 개 또는 여러 개의 jobs를 설정할 수 있다.
jobs:
  build:
    # 해당 workflow를 어떤 OS 환경에서 실행할 것인가?
    runs-on: ubuntu-latest
 #   env: 
 #     working-directory: ./1-nServer

    steps:
      - uses: actions/checkout@v2
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"
          #github_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Deploy to Koyeb
        run: koyeb service redeploy attendance/onlineattendance-api
